import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:http/http.dart' as http;
import 'dart:convert' as convert;
import '../provider/client_info.dart';
import '../service/http_fetchdata.dart';

class FetchData extends StatefulWidget {
  const FetchData({Key? key}) : super(key: key);

  @override
  _FetchDataState createState() => _FetchDataState();
}

class _FetchDataState extends State<FetchData> {
  @override
  void initState() {
    FetchProvider fetchProvider = Provider.of(context, listen: false);
    fetchProvider.getFetch();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    FetchProvider fetchProvider = Provider.of(context);
    return Scaffold(
      appBar: AppBar(
        title: Text(fetchProvider.autogenerated!.data!.email.toString()),
      ),
    );
  }
}
