import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:convert' as convert;
import '../model/fetch_model.dart';

@override
Future<Autogenerated?> getFetchData() async {
  try {
    String url = "https://reqres.in/api/users/2";
    http.Response response = await http.get(Uri.parse(url));
    if (response.statusCode == 200) {
      Map<String, dynamic> map = json.decode(response.body);
      Autogenerated? autogenerated =
          Autogenerated.fromJson(map as Map<String, dynamic>);
      return autogenerated;
    }
  } catch (e) {
    debugPrint("$e");
  }
}
