import 'package:flutter/cupertino.dart';

import '../model/fetch_model.dart';
import '../service/http_fetchdata.dart';

class FetchProvider extends ChangeNotifier {
  Autogenerated? autogenerated;

  getFetch() async {
    // isloading = true;
    var data = await getFetchData();
    autogenerated = data;
    // isloading = true;
    notifyListeners();
  }
}
